[package]
name = "static-preprocessing"
version= "1.0.0-alpha"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
tempfile = "3.20.0"
